name: Go

on:
  pull_request:
    branches: [master]

jobs:
  Automated-classdiagrams-gen:
    runs-on: ubuntu-latest
    env:
      PROTO_DIR: proto
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: "0.36.0"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Get protoc-gen-doc
        run: go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Test
        run: |
          protoc --doc_out=./generated-docs --doc_opt=html,index.html proto/*.proto

      - name: Read package.json
        id: filedata
        uses: juliangruber/read-file-action@v1
        with:
          path: ./generated-docs/index.html

      - name: format the string
        env:
          filedata: ${{ steps.filedata.outputs.content }}
        run: |
          filedata="${filedata//$'%'/%25}"
          filedata="${filedata//$'\n'/%0A}"
          filedata="${filedata//$'\r'/%0D}"

      - name: print data
        run: |
          echo "${{ env.filedata }}"

      - name: Make a curl request to Readme
        env:
          STEP_OUTPUT: ${{env.filedata}}
        run: |
          CODE=`curl --request POST \
              --url https://dash.readme.com/api/v1/docs \
              --header 'Accept: application/json' \
              --header 'Authorization: Basic cmRtZV94bjhzOWgwYWY3YTIwMGU3ZWY3YWIxZGJjMjBmYTkyMmI5ZDBmZGQ1NDAyMGEyYWE3OTQ3NGQ3MTk2ODliOGYyYmY4NjgwOg==' \
              --header 'Content-Type: application/json' \
              --data '{ \
                "hidden": true, \
                "order": 999, \
                "title": "Automation", \
                "type": "basic", \
                "body": "${{ env.STEP_OUTPUT }}", \
                "category": "62c5c1dd961ffc001afae149" \
              }'`
          echo "$CODE"    
          if [ $CODE!="200" ] 
          then
              echo "FAILURE"
          else
              echo "SUCCESS"
          fi
