name: Go

on:
  pull_request:
    branches: [master]

jobs:
  Automated-classdiagrams-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28

      - name: Get protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Get protoc-gen-doc
        run: go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Test
        run: |
          mkdir ./generated-docs
          protoc --doc_out=./generated-doc --doc_opt=html,index.html proto/*.proto

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "proto docs are generated"
          branch: master
