name: Go

on:
  pull_request:
    branches: [master]

jobs:
  Automated-classdiagrams-gen:
    runs-on: ubuntu-latest
    env:
      PROTO_DIR: proto
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: "0.36.0"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Get protoc-gen-doc
        run: go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Test
        run: |
          protoc --doc_out=./generated-docs --doc_opt=html,index.html proto/*.proto

      - name: Read package.json
        id: filedata
        uses: juliangruber/read-file-action@v1
        with:
          path: ./generated-docs/index.html

      - name: Echo package.json
        run: echo "${{ steps.filedata.outputs.content }}"

      - name: Make a curl request to Readme
        run: |
          CODE=`curl --request POST \
          --url https://dash.readme.com/api/v1/docs \
          --header 'Accept: application/json' \
          --header 'Authorization: Basic rdme_xn8s9h0af7a200e7ef7ab1dbc20fa922b9d0fdd54020a2aa79474d719689b8f2bf8680' \
          --header 'Content-Type: application/json' \
          --data '{
            "hidden": true,
            "order": 1,
            "error": {
                  "code": "string"
            },
            "title": "Automation Script",
            "type": "basic",
            "body": "${{ steps.filedata.outputs.content }}",
            "category": "62c5c1dd961ffc001afae149"
          }'`

          if [ $CODE!="200" ] 
          then
              echo "FAILURE"
          else
              echo "SUCCESS"
          fi
