name: Go

on:
  pull_request:
    branches: [master]

jobs:
  Automated-classdiagrams-gen:
    runs-on: ubuntu-latest
    env:
      PROTO_DIR: proto
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: "0.36.0"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Get protoc-gen-doc
        run: go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
      - name: Test
        run: |
          mkdir ./generated-docs
          protoc --doc_out=./generated-doc --doc_opt=html,index.html proto/*.proto
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "proto docs are generated"
          branch: master
