name: Readme

on:
  push:
    branches: [test]

jobs:
  Readme-Docs-Upload:
    runs-on: ubuntu-latest
    env:
      PROTO_DIR: proto
    steps:
      - uses: actions/checkout@v2

      - uses: wizhi/setup-buf@v1
        with:
          version: "0.36.0"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Run protoc command
        run: |
          mkdir ./grpc-doc
          protoc --doc_out=./grpc-doc --doc_opt=markdown,index.md proto/*.proto

      - name: Create header file
        run: |
          cat ./category.md
          echo "---
          title: Syncing Docs
          excerpt: Update your docs automatically with `rdme`, ReadMe's official CLI and GitHub Action!
          category: 62c5c1dd961ffc001afae149
          ---
          " > ./category.md
        shell: bash

      - name: Show category file content
        run: |
          cat ./category.md

      - name: Add category to md file
        run: |
          cat ./script/category.md ./grpc-doc/index.md > ./grpc-doc/index-new.md
        shell: bash

      - name: Show file content
        run: |
          rm ./grpc-doc/index.md
          ls ./grpc-doc
          cat ./grpc-doc/index-new.md

      - name: Sync docs to ReadMe
        uses: readmeio/rdme@main
        with:
          rdme: docs ./grpc-doc --key=rdme_xn8s9h0af7a200e7ef7ab1dbc20fa922b9d0fdd54020a2aa79474d719689b8f2bf8680 --version=1.0
