name: Sync `documentation` directory to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches: [test]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Let's dynamically update our docs with the latest version of rdme!
      # Note that these next three steps are not required
      # in order to sync your docs to ReadMe.

      # And finally, with our updated documentation,
      # we run the `rdme` GitHub Action to sync the Markdown file
      # in the `documentation` directory.
      # Here's the page we're syncing: https://docs.readme.com/docs/rdme
      - name: Sync docs to ReadMe
        # We use the `main` branch as ref for GitHub Action
        # This is NOT recommended, as it can break your workflows without notice!
        # We recommend specifying a fixed version, i.e. @7.0
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@main
        with:
          rdme: docs ./documentation --key=${{ secrets.README_DEVELOPERS_API_KEY }} --version=1.0
