name: Readme

on:
  push:
    branches: [test]

jobs:
  Readme-Docs-Upload:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      PROTO_DIR: proto
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: "0.36.0"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Run protoc command
        run: |
          mkdir -p documents
          protoc --doc_out=./documents --doc_opt=markdown,doc-index.md proto/*.proto

      - name: Check category.md file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "category.md"

      - name: Create header file
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          touch ./category.txt
          echo "---
          title: Syncing Docs demo
          excerpt: Update your docs automatically with `rdme`, ReadMe's official CLI and GitHub Action!
          category: ${{ secrets.README_API_DEFINITION_ID }}
          ---
          " > ./category.txt
        shell: bash

      - name: get all the .md files.
        id: check_files1
        run: |
          echo "::set-output name=FILELIST::$(ls ./documents -1p | grep -v / | xargs echo | sed 's/ /,/g')"

      - name: Adding readme header details(Category Id) to the md files
        run: |
          IFS="," read -a myarray <<< ${{ steps.check_files1.outputs.FILELIST }}
          for i in "${myarray[@]}"; do
            cat ./category.txt ./documents/${i} > ./documents/release-${i}
            rm ./documents/${i}
          done

      - name: Sync docs to ReadMe
        uses: readmeio/rdme@main
        with:
          rdme: docs ./documents  --key=${{ secrets.README_DEVELOPERS_API_KEY }} --version=1.0
